# Generated by Django 3.2.6 on 2021-08-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_test_app', '0004_auto_20210825_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='web_test_app.Tag'),
        ),
    ]
